-- 메모리DB는 애플리케이션이 종료될 때 함꼐 사라지기 때문에, 애플리케이션 실행 시점에 데이터베이스 테이블도 새로 만들어줘야한다.
-- JDBC나 JdbcTemplate도 가능하지만 너무 불편..
-- 스프링부트는 SQL스크립트를 실행해서 애플리케이션 로딩 시점에 데이터베이스를 초기화하는 기능을 제공
drop table if exists item CASCADE;
create table item
(
    id bigint generated by default as identity,
    item_name varchar(10),
    price integer,
    quantity integer,
    primary key (id)
);